### ISSUE TITLE
GraphQL Language Service master task

### ISSUE THREAD

**Issue by asiandrummer** [graphql/graphql-language-service#3]
## TODO before the release
- [x] Complete test suites imported from `codemirror-graphql` and written for server/configuration/utils.
  - [ ] Improve test suites for the parser
- [x] Command-line interface improvement to support locating `.graphqlrc`
- [x] Better error Handling - find erroneous use cases that exits the server or sends a RPC message with 'error' type.

## Nice-to-haves before/after the release
- [ ] caching unsaved/edited file contents in `GraphQLCache`.
- [x] Custom validation rules
- [ ] pretty-printed CLI outputs

Also, I'm not sure where this one fits but https://code.visualstudio.com/blogs/2016/06/27/common-language-protocol summarizes the architecture for implemented GraphQL server interface pretty well as a superset. It's probably worth mentioning and finding a place to collaborate with this protocol.

Please feel free to add/edit the items above.

**Comment by jimkyndemeyer** [comment]
I'm worried that https://github.com/facebook/watchman/issues/19 is still open. While I use a mac at work, I do have a PC at home, and cutting off the Windows developers seems like a bad idea.

**Comment by wincent** [comment]
As this issue is super old now, going to close it. Any remaining items we want to deal with can get issues of their own.
